# 不使用優化器來挑整參數


In [1]:
import torch

c:\Users\Wen2Tee5\Desktop\MLProject\ML\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
a = torch.randn(size=(3,5))
b = torch.randn(size=(5,3))

In [3]:
a @ b 

tensor([[ 2.1902, -1.8668,  3.3960],
        [-1.9020,  0.7958, -1.1476],
        [ 2.2420,  0.5306,  1.3647]])

# 根據基本機器學習公式來最佳化參數
## $$y=xW+b$$
## $$x\in\Bbb{R^5}$$ $$W\in\Bbb{R^{5*1}}$$ $$b\in\Bbb{R^1}$$
給定一個$y$跟$x$透過梯度下降法的找$W$跟$b$

In [2]:
LEARNING_RATE = 1e-1
y = torch.tensor([20.])
x = torch.ones((5)).to(torch.float32)
w = torch.randn(size=(5, 1), requires_grad = True)
b = torch.randn(size=(1,), requires_grad = True)
loss_fn = torch.nn.MSELoss()

In [3]:
w

tensor([[ 0.8089],
        [ 2.4063],
        [-0.2438],
        [ 0.8353],
        [-1.9821]], requires_grad=True)

In [4]:
b

tensor([-0.4953], requires_grad=True)

In [5]:
for epoch in range(10):
    z = x @ w + b
    loss = loss_fn(z, y)
    loss.backward()
    print("===========================")
    print(f'Loss value is {loss.item()}')
    print(f'y = {y}')
    print(f'z = {z}')
    with torch.no_grad():
        w = w - LEARNING_RATE * w.grad.data
        b = b - LEARNING_RATE * b.grad.data
    w.requires_grad = True
    b.requires_grad = True

Loss value is 348.5943298339844
y = tensor([20.])
z = tensor([1.3293], grad_fn=<AddBackward0>)
Loss value is 13.94377613067627
y = tensor([20.])
z = tensor([23.7341], grad_fn=<AddBackward0>)
Loss value is 0.5577521920204163
y = tensor([20.])
z = tensor([19.2532], grad_fn=<AddBackward0>)
Loss value is 0.02231031470000744
y = tensor([20.])
z = tensor([20.1494], grad_fn=<AddBackward0>)
Loss value is 0.000892275886144489
y = tensor([20.])
z = tensor([19.9701], grad_fn=<AddBackward0>)
Loss value is 3.5663691960508004e-05
y = tensor([20.])
z = tensor([20.0060], grad_fn=<AddBackward0>)
Loss value is 1.4210854715202004e-06
y = tensor([20.])
z = tensor([19.9988], grad_fn=<AddBackward0>)
Loss value is 5.6843418860808015e-08
y = tensor([20.])
z = tensor([20.0002], grad_fn=<AddBackward0>)
Loss value is 2.2737367544323206e-09
y = tensor([20.])
z = tensor([20.0000], grad_fn=<AddBackward0>)
Loss value is 9.094947017729282e-11
y = tensor([20.])
z = tensor([20.0000], grad_fn=<AddBackward0>)


In [6]:
w

tensor([[3.9207],
        [5.5181],
        [2.8680],
        [3.9471],
        [1.1297]], requires_grad=True)

In [7]:
b

tensor([2.6165], requires_grad=True)